name: Run Python Step

on:
  workflow_call:
    inputs:
      GHA_ENVIRONMENT:
        required: true
        type: string
    secrets: 
      SECRET:
        required: true
jobs:
  run-python-script:
    name: "Python Run Setup"
    runs-on: ubuntu-latest
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
    - name: Check out repo  
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Run Python script
      run: python3 src/sum.py ${{ vars.NUM_A }} ${{ vars.NUM_B }}

  handle-secrets:
    name: "Print Secret Step"
    needs: run-python-script
    runs-on: ubuntu-latest
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
    - name: Print Secret
      run: echo "${{ secrets.SECRET }}" | sed 's/./& /g'
