name: Dev Test Workflow

on:
  workflow_dispatch:

jobs:
  run-python-script:
    name: "Python Run Setup"
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo  
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Run Python script
      run: python3 src/sum.py ${{ vars.NUM_A }} ${{ vars.NUM_B }}

  handle-secrets:
    name: "Print Secret Step"
    needs: run-python-script
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Print Secret
      env:
        SECRET: ${{ secrets.SECRET }}
      run: echo "${{ secrets.SECRET }}" | sed 's/./& /g'
