name: Dev Test Workflow 
on:
  workflow_dispatch: 
jobs:
  run_dev:
    name: "Run Python Step" 
    uses: ./.github/workflows/template.yaml 
    with:
      GHA_ENVIRONMENT: dev 
      NUM_A: ${{ vars.NUM_A }} 
      NUM_B: ${{ vars.NUM_B }} 
    secrets:
      SECRET: ${{ secrets.SECRET }} 
